### PR TITLE
reset any index if its version was bumped

### PR DESCRIPTION
**Pull request by staltz**
:x: :heavy_check_mark:

### CODE REVIEW

**Comment by arj03** [comment]
So you are moving version around so that whenever you put something in indexes[] it must have a version, right? I thought I found a bug related to lazy loaded indexes but I can see that once it is loaded the version will be assigned. I'm really afraid that we make a mistake somewhere and forget this version number. There are only really 2 places ([1](https://github.com/ssb-ngi-pointer/jitdb/blob/64a67028618453cc5c2f912a320ff1a6a7e40107/files.js#L54), [2](https://github.com/ssb-ngi-pointer/jitdb/blob/64a67028618453cc5c2f912a320ff1a6a7e40107/files.js#L92)) in files.js where this is used when saving. What do you think about adding a `|| 1` there as a safeguard?

**Comment by staltz** [comment]
Yeah I can add the safeguard. The reason why I removed it was actually to surface additional bugs in those cases where `index.version` does not exist, just to make sure that we have `index.version` defined in all cases.

Alternatively, I can also do something like throw an error in files.js in case version is not defined.

**Comment by arj03** [comment]
Throw is probably better

**Comment by staltz** [comment]
Updated!

**Review by arj03 — APPROVED** [review]
Assuming the tests pass :)

**Pull request merged**
