### PR TITLE
add test for negative limit given to paginate()

### PR DESCRIPTION
**Pull request by staltz**
1st test, 2nd fix

### CODE REVIEW

**Comment by staltz** [comment]
Hello CI, where are you

**Comment by staltz** [comment]
@arj03 CI is not running today, not sure why, but if you want you can run tests locally.

**Review by arj03 — APPROVED** [review]
This looks good. Thanks, simple fix.

**Comment by arj03** [comment]
While we are at it (in another PR). Should paginate(0) return 0 results instead of all as it currently does?

**Comment by staltz** [comment]
> While we are at it (in another PR). Should paginate(0) return 0 results instead of all as it currently does?

Yes, makes lot of sense. I'm not sure what part of the tests attempt limit=0, but I'll take a look.

**Pull request merged**
