### PR TITLE
Refactors related to Crc PR

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by arj03** [comment]
`detectMissingAndLazyIndexes` might be refactored even more. Not sure if it will harder to read then.

**Comment by staltz** [comment]
@arj03 How? What kind of changes are you imagining?

**Comment by arj03** [comment]
Seems like the 2 functions now do almost the same thing, so could be refactored to patch in the check in the equals branch.

**Comment by staltz** [comment]
What do you think of this one?

**Review by arj03 — APPROVED** [review]
Beautiful. Thank you

**Pull request merged**
