### PR TITLE
debugQuery also live queries

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by arj03** [comment]
I guess we can do that, but it's a bit different from the other queries in that the query doesn't really end. Anyway if this is useful then lets merge.

**Comment by staltz** [comment]
I'm trying to debug some live-related bugs. For instance:

- Load up the app, see the posts
- Press "like" on one post
- No like appears on the post
- Go to raw log screen
- See all the published msgs, there is no vote in sight

But if I restart the app, then the likes appear. (Note, I'm publishing all msgs via ssb-db1 and then migrate runs)

**Comment by staltz** [comment]
Lets leave this PR open for now, I'll let you know if I'm really confident about it.

**Comment by staltz** [comment]
Yeah I think this is useful, it helped me know when the response to a live query finally came through. It doesn't give duration stats, but that's not the main info I need out of these queries, mostly I need to know the shape of the `op` and the amount of msgs in the result

**Comment by staltz** [comment]
@arj03 Can haz merge?

**Review by arj03 — APPROVED** [review]

**Comment by arj03** [comment]
Sure, go ahead :)

**Pull request merged**
